### ISSUE TITLE
openvpn-exit not default

### ISSUE THREAD

**Issue by genofire** [FreifunkBremen/ansible#11]
openvpn-exit sollte mit parameter abschaltbar sein.
_Sollen die machen, die ein anderen exit implementieren/benötigen :stuck_out_tongue_winking_eye:_

**Comment by corny** [comment]
Wie wäre es mit zwei Playbooks? Ein Playbook mit `openvpn-exit` und eins ohne.

**Comment by genofire** [comment]
Hauptsache die Group bleibt gleich für z.B: https://github.com/FreifunkBremen/ansible/blob/master/roles/router-bird/templates/internal_ipv4.conf

**Comment by corny** [comment]
Gut, dafür muss ich wissen:
- Welche VPN-Server haben einen GRE-Exit?
- Welche VPN-Server haben einen OpenVPN-Exit?

**Comment by ghost** [comment]
Ich schreibe schon eine GRE-Rolle. Da aber niemand von uns die Daten der Tunnel auf Github haben wollen wird, muessen die irgendwo anders gespeichert werden - die aktuelle OpenVPN- und meine begonnene GRE-Rolle ermoeglichen es nur die Rollen fuer je einen VPN-Server laufen zu lassen. Dazu habe ich noch keine Idee.

**Comment by corny** [comment]
Dann brauchen wir ein Playbook, welches ausschließlich den GRE-Tunnel einrichtet.
Es könnte dann die Variablen per `--extra-vars` oder [interaktiv](https://docs.ansible.com/ansible/playbooks_prompts.html) entgegennehmen.

**Comment by ghost** [comment]
Ich versteh nicht wieso. Wir koennen doch pro Gateway setzen, ob OpenVPN oder GRE und dann die Daten uebergeben oder abfragen (moeglichst nur abfragen, wenn nicht uebergeben).

**Comment by corny** [comment]
Das Ausführen/Nicht-Ausführen von Rollen wird in Ansible über Playbooks geregelt. Was hältst du davon, die beiden exit-Rollen zusammenzufassen und in der main.yml zwei bedingte `include`-Actions (für GRE und OpenVPN) einzufügen?

**Comment by corny** [comment]
Erledigt durch 192e2b03105355caf2a3e83d4ccb851bf9b08bb3:
Einfach die Variable `exit: no` setzen.
