### ISSUE TITLE
common-Rolle splitten

### ISSUE THREAD

**Issue by corny** [FreifunkBremen/ansible#13]
Da ist mir zu viel drin. Ich brauch auf meinem Server keinen Midnight Commander, keine ZSH und ich nutze eher tmux als screen. Was davon wird _wirklich_ benötigt, damit der Exit läuft?

**Comment by genofire** [comment]
Benötigt wird auf jeden Fall (wurde aus Rolen dahin verschoben):
- ethtool
- git
- iptables-persistent
- jq
- xtables-addons-dkms

Doppelt durch Role:
- chrony

**Comment by corny** [comment]
Pakete sollten von den Rollen installiert werden, die sie benötigen. Sonst sind die Abhängigkeiten total unklar.

**Comment by genofire** [comment]
80% der Rollen benutzen z.B. git.
Daher wurde die role tools-net, tools-system erstellt und am Ende zu common zusammengefasst.

**Comment by corny** [comment]
Ok, dann erstellen wir eine zweite Rolle für die Pakete, die nicht zwingend benötigt werden (z.B. `common-additional`). Die common-Rolle sollte im Playbook nicht direkt, sondern nur über die Meta-Dependencies eingebunden werden.

**Comment by genofire** [comment]
da `common` nicht mehr im playbook ist - ein quick fix:
https://github.com/FreifunkBremen/ansible/commit/649b519f381f35988af46dd4b4b51441de744c1f

**Comment by ghost** [comment]
Wie zieh ich die common rolle fuer meinen Server mit?

**Comment by genofire** [comment]
"This is not a personal ansible repository" :P
