### ISSUE TITLE
no-logging policy einbauen

### ISSUE THREAD

**Issue by anon6789** [FreifunkBremen/ansible#17]
jeden dienst nochmal so konfigurieren, dass er nicht loggt (vor allem dhcp)

**Comment by ghost** [comment]
Das einfachste waere busybox-syslogd. Der loggt in einem Ringpuffer und nienienie auf die Platte. Meinungen?

**Comment by corny** [comment]
Hört sich gut an. Funktioniert das auch zusammen mit Systemd?

**Comment by ghost** [comment]
Was hat systemd mit syslog zu tun?

**Comment by jplitza** [comment]
Um deine Frage zu beantworten: Es muss es ein Unit-File geben, das ihn startet.
Zum Anderen halte ich es für übertrieben, nichts auf die Platte zu loggen. Ich finde es wichtig festzustellen, seit wann z.B. im Log auftaucht "fastd: recvmsg: Temporarily unavailable" (oder was das war).
Und wer systemd mag (also z.B. ich) würde vermutlich lieber systemd-journald nutzen. Das loggt nämlich standardmäßig auch nicht auf die Platte, bietet dabei aber sehr viel mehr Komfort als busybox-syslogd.

**Comment by corny** [comment]
Ich mag auch systemd und bevorzuge deshalb ebenso `systemd-journald`.

**Comment by ghost** [comment]
Gut. Dann systemd mit so konfigurierten journald dass es nur im RAM landet?

**Comment by ghost** [comment]
Das war ne Frage...

**Comment by corny** [comment]
:+1:  muss nur noch jemand umsetzen.

**Comment by ghost** [comment]
Ja. Das war meine Frage. Mach ich nachher

**Comment by jplitza** [comment]
Ich bin immer noch der Meinung, dass es nicht zielführend ist, einfach global nichts auf die Platte zu loggen.

**Comment by corny** [comment]
Wovon wollen wir keine Logs auf der Platte? von fastd?

**Comment by jplitza** [comment]
Wir wollen _keine Logs_ (unabhängig davon, ob auf Platte oder im RAM, mMn) von allem, was personenbezogene Daten beinhaltet. Also insbesondere dem DHCP-Server und fastd-Verbindungen. Ich halte es im Gegenteil für sehr sinnvoll Logs allgemein zu haben, auch von fastd (siehe recvmsg-Problem).

**Comment by ghost** [comment]
- NSD verbosity auf 0 gesetzt
- dnsmasq loggt kein dhcp
- unbound hat auch verbosity von 0

mMn:
- wollen wir keine Logs auf Platte (+1): #27
- wollen wir Logs auf Platte: closed

**Comment by jplitza** [comment]
Habe nach Absprache #27 geschlossen, ebenso dieses, da wir Logs nicht generell abschalten wollen sondern nur den Diensten mit Nutzerdaten das Logging abgewöhnen wollen.
