### ISSUE TITLE
Fehlt nicht fastd-ffhb?

### ISSUE THREAD

**Issue by genofire** [FreifunkBremen/ansible#2]
src=fastd-ffhb

**Comment by jplitza** [comment]
Das hier ist nur ein minimaler Anfang, der zum Fortführen anregen soll. @mortzu wollte sich darum kümmern.

Da noch so ziemlich alles fehlt macht es keinen Sinn, aufzulisten was noch fehlt. Daher mache ich das Issue einfach mal zu.
