### ISSUE TITLE
services do not run correctly

### ISSUE THREAD

**Issue by genofire** [FreifunkBremen/ansible#28]
`linux-header` musste manuelle installiert werden.
Damit `/etc/kernel/postinst.d/dkms-batman-adv-downgrade $(uname -r)` ausgeführt werden konnte.
Zudem muss auch `batctl` auch installiert werden.

**Comment by genofire** [comment]
okay, das galt auch für den neu aufgesetzten vpn06 :( - da muss noch was getan werden

**Comment by corny** [comment]
@mortzu @jplitza Ist `linux-headers-amd64` das korrekte Metapaket, das wir installieren wollen?

**Comment by ghost** [comment]
jo

**Comment by ghost** [comment]
a318c3616512dd4b9c6291edf3ea94a68ea879a2

**Comment by ghost** [comment]
-> close

**Comment by genofire** [comment]
Wird `batctl` nun auch mit installiert? ^^

**Comment by ghost** [comment]
Jetzt ja
