### ISSUE TITLE
Extract fastd peers from site.conf

### ISSUE THREAD

**Issue by jplitza** [FreifunkBremen/ansible#3]
Let ansible generate the fastd peer information (public key and address) from the site.conf, for example by including the site repo as a submodule or by fetching the site.conf file directly via HTTP.

**Comment by corny** [comment]
Do you know a parser in python to parse the site.conf?

**Comment by genofire** [comment]
It is just JSON

Something like:

``` python
import json

obj_json=open('site.conf').read()
obj = json.loads(obj_json)

obj['fastd_mesh_vpn']['groups']['backbone']['peers']....
obj['ntp_servers']....

json.dumps(obj, indent=4) //indent fürs schöne Einrücken :)
```

**Comment by jplitza** [comment]
The site.conf isn't JSON in any way. It uses `=` as kay/value-separator, `--` for comments (JSON doesn't allow comments at all) and `{}` for lists.

No, it is actually valid Lua, because all software on the nodes is in Lua. And no, I don't know any parsers.

**Comment by genofire** [comment]
oO, to much JSON in my World the last Time.
replace `=` with `:` and delete after `--` :D
I know bad, because u lose comments.

**Comment by jplitza** [comment]
`apt-get install python-lua`

``` python
import lua
env = lua.lua()
conf = env.run("return " + open("site.conf").read())[0]
conf['fastd_mesh_vpn']['groups']['backbone']['peers']['vpn01']['key']
```

Note that `conf` is a `lua.Table`, a mixture of dict and list. You can use it with indices like usual python objects, but for viewing them, calling `.dict()` or `.list()` on them is required.

**Comment by corny** [comment]
I get the error `OSError: liblua5.1.so: cannot open shared object file: No such file or directory`
The package `python-lua` is installed and a `/usr/lib/x86_64-linux-gnu/liblua5.1.so.0` exists. It fails on a ubuntu 14.04.

You can find my code at https://github.com/FreifunkBremen/ansible/tree/uri_lua-test

**Comment by jplitza** [comment]
Indeed, 14.04 is missing a symlink. Simply create it yourself and it will work:
`ln -s /usr/lib/x86_64-linux-gnu/liblua5.1.so.0.0.0 /usr/lib/x86_64-linux-gnu/liblua5.1.so`
