### ISSUE TITLE
dnsmasq ersetzen

### ISSUE THREAD

**Issue by jplitza** [FreifunkBremen/ansible#30]
[dnsmasq kann maximal 1000 Leases verwalten](https://wiki.gentoo.org/wiki/Dnsmasq), weshalb vpn02 seit ner Weile nur noch sporadisch Leases verteilt (nach meinen eigenen Erfahrungen):

```
root@vpn02 ~ # wc -l /var/lib/misc/dnsmasq.leases
1000 /var/lib/misc/dnsmasq.leases
```

Das lässt sich schwer kontrollieren, wie viele Leases so ein Server vergeben muss. vpn02 hat momentan "nur" ~170 verbundene Knoten. Also müssen wir wohl bald mal dnsmasq ersetzen. @mortzu was sprach nochmal gegen isc-dhcp-server?

**Comment by ghost** [comment]
Dass er dauernd abgekackt ist?!

**Comment by jplitza** [comment]
Na gut, das Limit war wohl doch nicht so fix wie ich dachte. Dann ist das ja anscheinend erstmal vom Tisch.
