### ISSUE TITLE
fastd_key on ansible version 2.0

### ISSUE THREAD

**Issue by genofire** [FreifunkBremen/ansible#31]
```
TASK [fastd : Generate fastd secret] *******************************************
fatal: [vpn05.bremen.freifunk.net]: FAILED! => {"changed": false, "failed": true, "msg": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1443957786.02-208080378397601/fastd_key\", line 23, in <module>\r\n    with os.fdopen(os.open(path, os.O_WRONLY | os.O_CREAT, 0600), 'w') as handle:\r\nOSError: [Errno 2] No such file or directory: ''\r\n", "parsed": false}
```

**Comment by corny** [comment]
Wurde das Verzeichnis für die Datei vorher angelegt?

**Comment by genofire** [comment]
Nope, sollte ja aber ansible selbst machen :( - (als das Verzeichnis: /root/.ansible/tmp/ansible-tmp-1443957786.02-208080378397601/)
Mal sehen, hab erstmal wieder ansible 1.9.3 laufen.

Sollten wir bloß im Auge behalten, sobald ansible 2.0 als stable rauskommt (auf archlinux :P )

**Comment by ghost** [comment]
Nicht immer bleeding edge git foo nehmen? Im normalen Archlinux repo ist die 1er Version

**Comment by ghost** [comment]
-> close

**Comment by genofire** [comment]
Nun da ansible offiziell version 2 ist ...

```
TASK [fastd : Generate fastd secret] *******************************************
fatal: [ffhb.sum7.de]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1452888696.23-56401720661108/fastd_key\", line 23, in <module>\r\n    with os.fdopen(os.open(path, os.O_WRONLY | os.O_CREAT, 0600), 'w') as handle:\r\nOSError: [Errno 2] No such file or directory: ''\r\n", "msg": "MODULE FAILURE", "parsed": false}
```

Der Ordner `/root/.ansible/tmp/ansible-tmp-1452888696.23-56401720661108/` existiert nicht.

**Comment by corny** [comment]
Dann müssen wir im Playbook dafür sorgen, dass das Verzeichnis existiert.

**Comment by ghost** [comment]
Es hat die letzten male bei mir funktioniert

**Comment by corny** [comment]
Habe ich gefixt in 3566500cb10c756868ef1837dd40613c367d532b
