### ISSUE TITLE
Raise net.ipv4.netfilter.ip_conntrack_max

### ISSUE THREAD

**Issue by jplitza** [FreifunkBremen/ansible#33]
On vpn01 we just had floods of the following kernel message in the log:

```
nf_conntrack: table full, dropping packet
```

Thus we should probably raise the value of net.ipv4.netfilter.ip_conntrack_max, which defaults to something like 32000. Does 65536 seem like a sensible choice to you for the moment?

**Comment by genofire** [comment]
It still sounds small:
`CONNTRACK_MAX = RAMSIZE (in bytes) / 16384 / (x / 32)` where x is the number of bits in a pointer (for example, 32 or 64 bits)  [https://wiki.khnet.info/index.php/Conntrack_tuning]

But it is better than nothing.

**Comment by ghost** [comment]
Habs eben auf vpn01 auf 65536 gesetzt. Bootfest

**Comment by jplitza** [comment]
vpn02 just died of the same problem. Apparently I only set the value on vpn01.

@genofire That formula describes the default value. Setting the value to 65536 means the server can track 65536 connections, full stop.
As we are mostly talking about NATing to a single address here (right?), much more shouldn't make sense, because every connection will need a source port and there are only 65536 ports (right?). So at most twice that amount (TCP+UDP) could be needed, maybe plus some bits for external connections like fastd.

Alternatively, on hosts where we do not need to NAT (vpn02, in particular), we could refrain from using stateful packet filtering altogether (meaning we would drop the ipp2p stuff).

**Comment by ghost** [comment]
Warum schreiben wir auf englisch? Ich find das eher anstrengend...

**Comment by ghost** [comment]
Wieso brauchen wir auf vpn02 kein NAT? Und das muesste dann auch ansibilisiert werden

**Comment by jplitza** [comment]
Unser vpn02 benutzt den Berliner Uplink vpn03, dessen Policy NAT explizit verbietet. Der Berliner vpn03 macht selbst NAT ins Internet, aber möchte pro echtem Client eine IP-Adresse sehen. Sonst greifen deren Filter etc. ggf. gegen alle Bremer Nutzer, statt nur gegen ein Endgerät.

**Comment by ghost** [comment]
Achja. Da war ja was. Also n NAT flag im Ansible? Und wenn NAT: 65536+1000 oder so?

**Comment by jplitza** [comment]
Mindestens auf vpn02 wurden die sysctls immer noch nicht beim Boot gesetzt, obwohl `nf_conntrack_ipv4` in der `/etc/modules` steht. Ich hab daher jetzt auf vpn0[123] in die `/etc/rc.local` am Ende eingebaut:

```
sysctl -p /etc/sysctl.d/ipv4-netfilter-ip-conntrack-max.conf
```

Ne wirkliche Lösung ist das aber nicht, und auf anderen Gateways klappt es teilweise auch mit dem Setzen beim Boot ohne diese Zeile. Ich weiß nicht, was da los ist...

**Comment by ghost** [comment]
In Ansible hakish geloest: a5961bd8d2bbeeb74600854df506e10e53834f22
