### ISSUE TITLE
blacklist.sh kopieren und aufrufen statt direkt aufrufen

### ISSUE THREAD

**Issue by jplitza** [FreifunkBremen/ansible#37]
Momentan wird von der fastd-Rolle das vpn-blacklist Repo nach /opt geclont und fastd ruft dann dort das blacklist.sh-Script auf. Leider wird das Repo auch per Cronjob aktuell gehalten, sodass man einfach nur auf Github das Script ändern muss um spätestens eine Stunde später alle Server geownt zu haben. Wir müssen also stattdessen das Script irgendwo hin kopieren und dort ausführen.

**Comment by ghost** [comment]
Fixed in 32b8ab5e02726ee70f5410c2561d3524d28ef1bb
