### ISSUE TITLE
Update repositories with scripts?

### ISSUE THREAD

**Issue by jplitza** [FreifunkBremen/ansible#4]
We have repositories from which we autoexecute scripts (at least icvpn-scripts). These definitely shouldn't be updated via cron. However, do we want to update them on execution of the playbook? Or ensure a specific commit?

**Comment by ghost** [comment]
Update it to a specific (reviewed) commit on ansible run

**Comment by corny** [comment]
I like that idea.

**Comment by genofire** [comment]
should we write this rule somewhere down?

Could we close this issue now? Or should somebody set every git clone inte playbooks to a commit?

**Comment by jplitza** [comment]
Yep, we need to ping every repo to a commit before we close this.
