### ISSUE TITLE
Unbenutzte Rollen

### ISSUE THREAD

**Issue by jplitza** [FreifunkBremen/ansible#42]
Wofür sind die folgenden Rollen da?
- `etckeeper`:
  Nicht nur wird die nicht verwendet, mir erscheint die Kombination von etckeeper und Ansible auch nicht sonderlich sinnvoll: Alle wichtige Config sollte in Ansible verwaltet werden und folglich auch hier versioniert. Wenn etckeeper trotzdem sein muss, müsste Ansible zumindest entsprechend damit interagieren (nach Änderungen in /etc einen Commit ausführen)
- `mysql` & `automysqlbackup`:
  Nirgends in der gesamten Freifunk-Infrastruktur verwenden wir MySQL, oder? o_O Auch keine von den Rollen oder Hostgroups hier (außer PHP aus mir ebenfalls unbekanntem Grund) referenziert MySQL.

**Comment by genofire** [comment]
:+1: nein, mysql muss man unter php immer erst als extension in der php.ini einbinden (auskommentieren).

Brauche wir `PHP`?

`nodeJS` kann auch weg, wenn jemand das hier verifiziert: https://github.com/FreifunkBremen/meshviewer/pull/2

**Comment by ghost** [comment]
php brauchen wir. rest guck ich

**Comment by ghost** [comment]
MySQL braucht phabricator

**Comment by oliver** [comment]
Etckeeper find ich auch ohne Ansible-Integration immer noch hilfreich, weil man sieht, was halt so alles händisch verändert wurde. Und es entstehen wohl keine Nachteile durch etckeeper. Ich würds deshalb lieber behalten.

**Comment by ghost** [comment]
Ich sehe das mit etckeeper genauso wie oliver!

**Comment by jplitza** [comment]
Dann muss das aber irgendwie besser integriert werden. Insbesondere muss etckeeper so konfiguriert werden, dass er rundherum um nen apt-Lauf einfach nichts tut (also weder vorher committet, noch ihn blockiert, noch hinterher committet, oder aber vorher stashen und hinterher committen). Dafür sollte vermutlich vor dem Ansible-Run einmal sichergestellt werden, dass alles committet ist, und am Ende alle Änderungen automatisch committet werden.
