### ISSUE TITLE
roles/wiki: Gollum wird nicht gestartet

### ISSUE THREAD

**Issue by jplitza** [FreifunkBremen/ansible#43]
Es gibt zwar eine Datei `files/run`, die Gollum starten soll, die wird aber nicht mal auf den Host kopiert, geschweige denn automatisch gestartet.

Sollte das einfach per Cronjob mit `@reboot` geschehen?

**Comment by ghost** [comment]
Jaaa. Ich bin noch nicht so weit... ;)

**Comment by ghost** [comment]
Fixed mit 6205c4881b21509e7afa488280c4764697501189
