### ISSUE TITLE
fastd-backbone eliminieren

### ISSUE THREAD

**Issue by jplitza** [FreifunkBremen/ansible#49]
[fastd v18 kann jetzt unbekannte Peers in ne Peergroup schieben](https://fastd.readthedocs.org/en/v18/releases/v18.html#more-powerful-peer-groups). Damit kann man auch das Peerlimit nur für unbekannte Peers gelten lassen. Folglich ist die Motivation für die separate fastd-backbone-Instanz hinfällig, oder?

**Comment by corny** [comment]
Richtig, so ist es.

**Comment by ghost** [comment]
Nein. fastd kann nur je einen Kern nutzen. Ich hab gestern Nacht ein wenig unser Netz debugged und die seperate Instanz koennte ein paar unserer Probleme loesen

**Comment by corny** [comment]
Ich bin eh dafür, dass wir GRE oder IPSec mit raw RSA-Keys für das Backbone nutzen.

**Comment by jplitza** [comment]
Für den Backbone brauchen wir keine Verschlüsselung, aber GRE ist nur Layer 3, wir brauchen Layer 2, und laut @mortzu ist gretap eklig. Kenne mich da (noch) nicht aus, fände aber auch eine in-kernel-Lösung besser.

**Comment by corny** [comment]
@mortzu was ist an gretap ekelig?

**Comment by ghost** [comment]
"gretap does not fragment IP packets" - ist das ein Problem?

**Comment by jplitza** [comment]
Nope, wir würden über die gretap-Tunnel ja batman-adv sprechen, das liest die MTU des Tunnels selbst aus und fragmentiert entsprechend (davon abgesehen dass es Pakete vom fastd-VPN weiterleiten würde, die bei richtiger MTU-Wahl eh schon auf die richtige Größe fragmentiert sind).

**Comment by corny** [comment]
Dann mach ich mal einen neuen Branch für die gretap-Tunnel? Ich hab da schon was fertig für meine eigenen Server (nicht Freifunk).
