### ISSUE TITLE
nsd: Cannot assign requested address

### ISSUE THREAD

**Issue by jplitza** [FreifunkBremen/ansible#65]
Auf dem DNS-Server kam nach einem Neustart der nsd nicht hoch mit folgenden Einträgen im Log:

```
Jun 15 12:00:46 dns nsd[324]: can't bind udp socket: Cannot assign requested address
Jun 15 12:00:46 dns nsd[324]: [2016-06-15 12:00:46.643] nsd[324]: error: can't bind udp socket: Cannot assign requested address
Jun 15 12:00:46 dns nsd[324]: server initialization failed, nsd could not be started
Jun 15 12:00:46 dns nsd[324]: [2016-06-15 12:00:46.644] nsd[324]: error: server initialization failed, nsd could not be started
```

Das liegt höchstwahrscheinlich daran, dass [in der nsd.conf](https://github.com/FreifunkBremen/ansible/blob/master/roles/nsd/templates/nsd.conf#L5-10) auf feste Adressen gebunden wird. Brauchen wir das noch, jetzt wo der nsd nicht mehr auf den VPN-Servern läuft?

**Comment by ghost** [comment]
Denke nicht. Denke der kann auch auf Wildcard lauschen. Just try it ;)

**Comment by jplitza** [comment]
Done, jetzt kommt der nsd nach nem Reboot auch ordentlich hoch (auch wenn er jetzt rumjammert, dass er keine Notifys senden konnte wegen Network unreachable, aber das ist denke ich nicht so dramatisch).
