### ISSUE TITLE
etckeeper besser integrieren

### ISSUE THREAD

**Issue by jplitza** [FreifunkBremen/ansible#69]
Es gibt ne nette [Rolle für etckeeper](https://github.com/expansible/etckeeper) die vor und nach dem Ansible-Run automatisch committet. Idealerweise könnte man noch ein kleines var_plugin schreiben, das in die Commit Message den aktuellen Commit des Ansible-Repos schreibt

**Comment by oliver** [comment]
Hab die verlinkte Rolle nicht im Detail untersucht; aber die grundsätzliche Idee find ich sehr gut!

**Comment by corny** [comment]
Ist das Problem mit #68 behoben?

**Comment by jplitza** [comment]
Nein, #68 ist was völlig anderes. Es geht darum, dass ein Ansible-Run hinterher automatisch "etckeeper commit" aufrufen sollte, idealerweise mit der Information welcher Commit des Ansible-Repos ausgeführt wurde. Und damit man keine Änderungen, die gar nicht aus dem Ansible-Run kommen, damit vermengt, sollte vorher auch committet werden oder Run failen falls es uncommitted changes gibt.

Im wesentlichen halt so wie sich eine Paket-Installation via apt bei installiertem etckeeper verhält. 😉
