### ISSUE TITLE
Firewall

### ISSUE THREAD

**Issue by genofire** [FreifunkBremen/ansible#7]
(kann ich mir noch vom vpn01 klauen, wird am freitag nebenbei gemacht)

**Comment by genofire** [comment]
Danke anon :) - sysctl wurde nun gemacht :D

**Comment by genofire** [comment]
Könntet ihr nochmal drüber schauen? (Ist nur in der Theorie entstanden und noch nicht getestet)
https://github.com/FreifunkBremen/ansible/tree/master/roles/firewall/templates

**Comment by corny** [comment]
Da würde ich mir noch eine Variable für das Netz wünschen:

```
-A POSTROUTING -s 10.196.0.0/16 -o {{ uplink_interface_name }} -j MASQUERADE
```

`{{ipv4_network_max}}` aus der `group_vars/all.yml` ist dein Freund.
Warum endet die überhaupt mit `_max`?

Benutz für Code-Reviews bitte grundsätzlich einen separaten Branch mit Pull-Request.

**Comment by genofire** [comment]
Uns gehört das /16 Netz, doch wir benutzen nur /17 - siehe z.B. DHCP-Server

**Comment by corny** [comment]
Dann reicht es, wenn wir das `/17` in die Variablen eintragen. Wie könnte man die sinnvoll umbenennen?

**Comment by genofire** [comment]
Garnicht, dafür wurde sie extra angelegt - ansonsten sollte sie von der `hosts` bzw. von der `lib/hosts.py` kommen und wieder `ipv4_network` heißen. (Sie müsste demnach auch noch in `roles/ntp-chrony/templates/chrony.conf` geändert werden)

**Comment by corny** [comment]
Die Idee gefällt mir. Hab einen Pull-Request für die Änderungen erstellt.

**Comment by corny** [comment]
Hatte schon jemand die Gelegenheit, die iptables-Konfiguration zu testen?

**Comment by genofire** [comment]
Deine Clean UPS wurde von anon und mir noch nicht getestet. Vielleicht @mortzu?
