### ISSUE TITLE
GRE over IPSec 

### ISSUE THREAD

**Issue by corny** [FreifunkBremen/ansible#70]
StrongSwan unterstützt ab Version [5.20](https://wiki.strongswan.org/versions/52) SSH public keys, so dass sich die Host-Keys von OpenSSH auch für IPSec verwenden lassen. Irgendwelche Bendenken?

**Comment by SimJoSt** [comment]
Gibt es Gründe dafür die GRE-Tunnel zu verschlüsseln? Es sieht ja so aus, dass (auch zukünftig) immer mehr VPN-Tunnel zu den Gateways selbst unverschlüsselt sind (sein werden).
Oder gibt es dafür keinen performance hit und es ist nice to have?

**Comment by corny** [comment]
Je mehr verschlüsselt wird, desto besser. Die Server haben wesentlich mehr Leistung, so dass sich IPSec ohne spürbare Geschwindigkeitsnachteile umsetzen lässt - vorausgesetzt es gibt ausreichend ungenutzte CPU-Ressourcen.

**Comment by jplitza** [comment]
Ich bezweifle, dass es diese ungenutzten CPU-Ressourcen gibt, und wenn sollten wir sie nicht mit Verschlüsselung verschwenden. Wir reden hier von dem Weiter-Transport eines im WLAN unverschlüsselten Netzes. Jegliche Art von Verschlüsselung ergibt meines Erachtens keinen Sinn.

**Comment by corny** [comment]
ok
