### ISSUE TITLE
Microfirewall ersetzen

### ISSUE THREAD

**Issue by genofire** [FreifunkBremen/ansible#73]

**Comment by corny** [comment]
Eine einfache und flexible Firewall wäre eine Sammlung von Scripten (Shell oder Python) in `/etc/firewall.d/`, die nach ihrer Reihenfolge/Priorität durchnummeriert sind und iptables-Aufrufe enthalten. Hilfsfunktionen, die ich z.B. in einem eigenen Firewall-Paket in unserer Firma verwende, sind:

```bash
ipt() {
  ipt4 $*
  ipt6 $*
}

ipt4() {
  iptables $* || echo iptables $*
}

ipt6() {
  ip6tables $* || echo ip6tables $*
}
```
Das vereinfacht das definieren von Regeln, die für beide IP-Versionen gelten.

**Comment by genofire** [comment]
Fehlt da noch ein flush?

da manches doch nur Versionsspezifisch ist, würde ich file extensions `.v4`,`.v6` und `.dual` Vorschlagen.

**Comment by jplitza** [comment]
@genofire Das Initskript würde etwa so aussehen:
```bash
for file in /etc/firewall.d/*; do
  . $file
done
```
Die von @corny gepostete Datei wäre dann z.B. `/etc/firewall.d/00-base`. Eine Datei `/etc/firewall.d/fastd` zum Beispiel könnte dann so aussehen:
```bash
ipt -N fastd
ipt -A INPUT -p udp --dport 50000 -j ACCEPT
ipt -A INPUT -p udp --dport 10000 -j ACCEPT
ipt6 -A fastd -s 2002::/16 -j REJECT --reject-width icmp6-adm-prohibited
ipt -A fastd -j ACCEPT
```
(das flush könnte man dann entweder in der `00-base` oder vielleicht sauberer in `01-flush` unterbringen)
