### ISSUE TITLE
Keine IPv6-Default-Route voraussetzen

### ISSUE THREAD

**Issue by jplitza** [FreifunkBremen/ansible#75]
Momentan setzt [roles/batman-adv-interface/templates/interrfaces](https://github.com/FreifunkBremen/ansible/blob/master/roles/batman-adv-interface/templates/interfaces#L13) eine IPv6-Default-Route voraus, um aus der MAC-Adresse des entsprechenden Interfaces die MAC-Adresse des Batman-Interfaces zu berechnen.

Da vpn02 keine IPv6-Default-Route hat, funktioniert diese Rolle dort momentan nicht.

**Comment by ghost** [comment]
Das wurde, wenn ich das richtig sehe, wieder kaputt gemacht: https://github.com/FreifunkBremen/ansible/commit/541d928832693d9f5044070d28d02de5594155b1#diff-ca267bbd09af2519b1fc57e50518c340

**Comment by genofire** [comment]
wenn wirklich
```
batadv-hw {{ ansible_default_ipv4.macaddress | derive_mac_addr(2) }}
```
richtig war, sry - bin von ein fehler ausgegangen
(da ich zu den zeitpunkt kein ipv4 hatte und ich mit mac immer an linklocal -> verbinde)
