### ISSUE TITLE
ffnord-alfred-announced → mesh-announce

### ISSUE THREAD

**Issue by jplitza** [FreifunkBremen/ansible#78]

**Comment by genofire** [comment]
Kann es im Juli machen

**Comment by genofire** [comment]
Also das neue url benutzen (https://github.com/ffnord/mesh-announce) und die beiden rollen zu einer zusammen zu fassen (wobei man immer noch einzeln auswählen kann, ob die daten per respondd oder alfred veröffentlicht werden wollen)
