### ISSUE TITLE
Error unbound bind on address twice

### ISSUE THREAD

**Issue by genofire** [FreifunkBremen/ansible#80]
https://github.com/FreifunkBremen/ansible/blob/f9135a94cfb47af50f939aa85422cb0be9d9dc6c/hosts#L9

https://github.com/FreifunkBremen/ansible/blob/6a4694a2dc0b54849a579ac8f7b899bac7ad46f4/lib/hosts.py#L36

https://github.com/FreifunkBremen/ansible/blob/410182cd087f4b0c03b6b07100e5e5dafbc154cb/roles/unbound/templates/listen-on-all-interfaces.conf#L5-L8

**Comment by jplitza** [comment]
Ja, Ansible geht davon aus, dass in der site.conf das globale Präfix steht. Das tut es aber gar nicht mehr.

**Comment by genofire** [comment]
Genau :+1: - das meinte ich.
