### ISSUE TITLE
Firewall restart does not work on debian-buster

### ISSUE THREAD

**Issue by genofire** [FreifunkBremen/ansible#92]
A kernel/iptables thing here:

https://github.com/FreifunkBremen/ansible/blob/fc2b6fd454a18b84aa3f4a0f793e9e480d86af78/roles/firewall/files/00-base#L2

Any idea how to fetch iptables tables on a other way?

**Comment by jplitza** [comment]
Switching to nftables would make sense.

**Comment by ghost** [comment]
```
iptables-save | grep '^*' | cut -d'*' -f2
```
