### ISSUE TITLE
debian10 - batman-adv-legacy

### ISSUE THREAD

**Issue by genofire** [FreifunkBremen/ansible#94]
the debian package of [universe-factory](https://repo.universe-factory.net/debian/) does not contain fixes:
- https://github.com/freifunk-gluon/batman-adv-legacy/commit/226f08ce9c2c2b2f966c1061ce4b80aafd744b7d

workaround (works on ffmap):
```bash
mv /usr/src/batman-adv-2013.4.0 /usr/src/batman-adv-2013.4.0.bak
git clone https://github.com/freifunk-gluon/batman-adv-legacy /usr/src/batman-adv-2013.4.0
/etc/kernel/postinst.d/dkms-batman-adv-downgrade $(uname -r)               
```

**Comment by ghost** [comment]
Sollte mit 28d7f98706ac9a1d8b0399c332c510dd17965e12 und a66c1c3ebeab22af5537ad4e7844324525fa68c7 und b4c35b6cae57c98b3287982b2363be6ea372e48e gefixt sein

**Comment by ghost** [comment]
@genofire ?
